### PR TITLE
Storybook 8 compatibility

### PR DESCRIPTION
**Pull request by evg4b**
Hi @geometricpanda, 
I have updated dependencies to support Storybook 8 (see issue #20).
Also, all deps were updated to the latest versions.

### CODE REVIEW

**Comment by jimdrury** [comment]
Ooh awesome. I'll review this later today

I've been talking with Storyblok about some changes to better work with Storyblok 8, but this also sounds great.

**Comment by bberto** [comment]
Hello @geometricpanda, any update on this? 
Thanks for this useful addon, and thanks @evg4b for the contribution!

**Comment by jimdrury** [comment]
Hey, I've just merged

**Comment by alexpthomasdev** [comment]
Hi @geometricpanda Thanks for merging!
Seems like it was an error on the package creating and the npm package wasn't release

**Comment by jimdrury** [comment]
I saw, it's on my todo list for today

**Comment by JamesIves** [comment]
Any updates on that version? 👀

**Comment by JamesIves** [comment]
@geometricpanda I've pushed up a PR that should hopefully resolve the publication workflow: https://github.com/geometricpanda/storybook-addon-badges/pull/23

**Comment by jimdrury** [comment]
Awesome thanks,

**Comment by JamesIves** [comment]
Odd, I am not sure why that didn't publish. [I tested this in my fork](https://github.com/JamesIves/storybook-addon-badges/actions/runs/8754407647/job/24026088028) and it worked as-is, all I did was add an NPM_TOKEN to my action secrets.

**Comment by JamesIves** [comment]
Not sure why that didn't publish. Tried to debug it more in my fork but it works every time I push to the main branch.

Possible issue with the `NPM_TOKEN` perhaps? Or maybe you need to re-run the workflow so it's not executed from a user besides yourself by making a minor change to the base branch?

**Pull request merged**
